#ifndef _PRESETDEFAULT_H_
#define _PRESETDEFAULT_H_

#include "presetSystem.h"


#define FLAG_DEFAULT_INPUT_SELECT			(AudioSwitchSelectorStereo::SIGNAL_SELECT_L)

#define PARAM_DEFAULT_COMP_PREGAIN 			(1.0f)
#define PARAM_DEFAULT_COMP_THRES 			(-20.0f)
#define PARAM_DEFAULT_COMP_RATIO 			(5.0f)
#define PARAM_DEFAULT_COMP_ATTACK 			(0.005f)
#define PARAM_DEFAULT_COMP_RELEASE			(0.2f)
#define PARAM_DEFAULT_COMP_POSTGAIN			(1.0f)

#define PARAM_DEFAULT_BOOST_DRIVE			(1.0f)
#define PARAM_DEFAULT_BOOST_BOTTOM			(1.0f)
#define PARAM_DEFAULT_BOOST_PRESENCE		(1.0f)
#define PARAM_DEFAULT_BOOST_MIX				(1.0f)
#define PARAM_DEFAULT_BOOST_LEVEL			(1.0f)

#define PARAM_DEFAULT_GATE_THRES			(-59.0f)
#define PARAM_DEFAULT_AMP_GAIN				(1.0f)
#define PARAM_DEFAULT_AMP_BASS				(1.0f)
#define PARAM_DEFAULT_AMP_MID				(1.0f)
#define PARAM_DEFAULT_AMP_TREBLE			(1.0f)
#define PARAM_DEFAULT_AMP_FXMIX				(0.2f)

#define PARAM_DEFAULT_DELAY_TIME			(0.6f)
#define PARAM_DEFAULT_DELAY_INERTIA			(0.0f)
#define PARAM_DEFAULT_DELAY_REPEATS			(0.4f)
#define PARAM_DEFAULT_DELAY_MIX				(1.0f)
#define PARAM_DEFAULT_DELAY_HICUT			(0.0f)
#define PARAM_DEFAULT_DELAY_LOWCUT			(0.0f)
#define PARAM_DEFAULT_DELAY_TREBLE			(1.0f)
#define PARAM_DEFAULT_DELAY_BASS			(1.0f)
#define PARAM_DEFAULT_DELAY_MODRATE			(0.0f)
#define PARAM_DEFAULT_DELAY_MODDEPTH		(0.0f)

#define PARAM_DEFAULT_REVERBPL_SIZE			(0.8f)
#define PARAM_DEFAULT_REVERBPL_DIFF			(1.0f)
#define PARAM_DEFAULT_REVERBPL_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBPL_BASSCUT		(0.0f)
#define PARAM_DEFAULT_REVERBPL_TREBLECUT	(0.0f)		
#define PARAM_DEFAULT_REVERBPL_TREBLE		(1.0f)
#define PARAM_DEFAULT_REVERBPL_BASS			(1.0f)
#define PARAM_DEFAULT_REVERBPL_BLEEDIN		(0.0f)
#define PARAM_DEFAULT_REVERBPL_PITCH		(0.0f)
#define PARAM_DEFAULT_REVERBPL_PITCHMIX		(0.0f)
#define PARAM_DEFAULT_REVERBPL_SHIMMER		(0.0f)
#define PARAM_DEFAULT_REVERBPL_PITCHSHIMM	(0.0f)

#define PARAM_DEFAULT_REVERBSC_TIME			(0.7f)
#define PARAM_DEFAULT_REVERBSC_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBSC_LOWPASSF		(1.0f)

#define PARAM_DEFAULT_REVERBSP_TIME			(0.7f)
#define PARAM_DEFAULT_REVERBSP_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBSP_BASSCUT		(0.4f)
#define PARAM_DEFAULT_REVERBSP_TREBLECUT	(0.3f)

#define PARAM_DEFAULT_MASTER_VOLUME			(1.0f)
#define PARAM_DEFAULT_MASTER_PAN			(0.0f)
#define PARAM_DEFAULT_DELAY_VOLUME			(0.2f)
#define PARAM_DEFAULT_REVERB_VOLUME			(0.2f)
#define PARAM_DEFAULT_MASTER_LOWCUT			(0.0f)

extern const preset_t presets_default[PRESET_MAX_NO];

#endif // _PRESETDEFAULT_H_
