#ifndef _MIDI_H_
#define _MIDI_H_

#include <Arduino.h>

// Callbacks for MIDI
void cb_ProgramChange(uint8_t channel, uint8_t program);
void cb_NoteOn(uint8_t channel, uint8_t note, uint8_t velocity);
void cb_ControlChange(uint8_t channel, uint8_t control, uint8_t value);
void cb_MidiClock(void);


// Control Change mapping
enum 
{
	// Delay controls
	MIDI_CC_DELAY_TIME				= 1,	
	MIDI_CC_DELAY_INERTIA			= 2,
	MIDI_CC_DELAY_FEEDBACK			= 3,
	MIDI_CC_DELAY_MIX				= 4,
	MIDI_CC_DELAY_MOD_RATE			= 5,
	MIDI_CC_DELAY_MOD_DEPTH			= 6,
	MIDI_CC_DELAY_TREBLE_CUT		= 7,
	MIDI_CC_DELAY_BASS_CUT			= 8,
	MIDI_CC_DELAY_TREBLE			= 9,
	MIDI_CC_DELAY_BASS				= 10,

	// wah controls
	MIDI_CC_WAH_FREQ				= 11,
	MIDI_CC_WAH_MIX					= 12,

	// Gate controls
	MIDI_CC_GATE_THRES				= 20,
	// Booster
	MIDI_CC_BOOST_GAIN				= 21,
	MIDI_CC_BOOST_BOTTOM			= 22,
	MIDI_CC_BOOST_PRESENCE			= 23,
	MIDI_CC_BOOST_MIX				= 24,
	MIDI_CC_BOOST_LEVEL				= 25,
	// Amp controls
	MIDI_CC_AMP_GAIN				= 30,
	MIDI_CC_AMP_BASS				= 31,
	MIDI_CC_AMP_MID					= 32,
	MIDI_CC_AMP_TREBLE				= 33,
	MIDI_CC_AMP_FXMIX				= 34,
	// Compressor
	MIDI_CC_COMP_PREGAIN			= 40,
	MIDI_CC_COMP_THRES				= 41,
	MIDI_CC_COMP_RATIO				= 42,
	MIDI_CC_COMP_ATTACK				= 43,
	MIDI_CC_COMP_RELEASE			= 44,
	MIDI_CC_COMP_POSTGAIN			= 45,
	// Reverb - Plate
	MIDI_CC_REVERBPL_TIME			= 50,
	MIDI_CC_REVERBPL_DIFF			= 51,
	MIDI_CC_REVERBPL_MIX			= 52,
	MIDI_CC_REVERBPL_BASS_CUT		= 53,
	MIDI_CC_REVERBPL_TREBLE_CUT		= 54,
	MIDI_CC_REVERBPL_BASS			= 55,
	MIDI_CC_REVERBPL_TREBLE			= 56,
	MIDI_CC_REVERBPL_BLEEDIN		= 57,
	MIDI_CC_REVERBPL_PITCH			= 58,
	MIDI_CC_REVERBPL_PITCHMIX		= 59,
	MIDI_CC_REVERBPL_SHIMMER		= 60,
	MIDI_CC_REVERBPL_SHIMM_PITCH	= 61,
	// ReverbSC
	MIDI_CC_REVERBSC_TIME			= 70,
	MIDI_CC_REVERBSC_MIX			= 71,
	MIDI_CC_REVERBSC_TREBLE			= 72,
	// Reverb - Spring
	MIDI_CC_REVERBSP_TIME			= 80,
	MIDI_CC_REVERBSP_MIX			= 81,
	MIDI_CC_REVERBSP_BASS_CUT		= 82,
	MIDI_CC_REVERBSP_TREBLE_CUT		= 83,

	MIDI_CC_MASTER_VOLUME			= 90,
	MIDI_CC_DELAY_REVERB_MIX		= 91,
	MIDI_CC_MASTER_PAN				= 92,
	MIDI_CC_MASTER_LOWCUT			= 93
};

enum
{
	// --- Amp + IR buttons ---
	MIDI_NOTEON_AMP_OFF				= 1,
	MIDI_NOTEON_AMP_CLN1			= 2,
	MIDI_NOTEON_AMP_CLN2			= 3,
	MIDI_NOTEON_AMP_CLN3			= 4,
	MIDI_NOTEON_AMP_CLN4			= 5,
	MIDI_NOTEON_AMP_CRUNCH1			= 6,
	MIDI_NOTEON_AMP_CRUNCH2			= 7,
	MIDI_NOTEON_AMP_LEAD1			= 8,
	MIDI_NOTEON_AMP_LEAD2			= 9,
	MIDI_NOTEON_IR_G1				= 10,
	MIDI_NOTEON_IR_G2				= 11,
	MIDI_NOTEON_IR_G3				= 12,
	MIDI_NOTEON_IR_G4				= 13,
	MIDI_NOTEON_IR_G5				= 14,
	MIDI_NOTEON_IR_G6				= 15,
	MIDI_NOTEON_IR_G7				= 16,
	MIDI_NOTEON_IR_B1				= 17,
	MIDI_NOTEON_IR_B2				= 18,
	MIDI_NOTEON_IR_B3				= 19,
	MIDI_NOTEON_IR_OFF				= 20,
	MIDI_NOTEON_IR_DOUBLER_TGL		= 21,
	MIDI_NOTEON_IR_DOUBLER_ON		= 22,
	MIDI_NOTEON_IR_DOUBLER_OFF		= 23,
	// --- Compressor ---
	MIDI_NOTEON_COMP_TGL			= 24,
	MIDI_NOTEON_COMP_ON				= 25,
	MIDI_NOTEON_COMP_OFF			= 26,
	// --- Booster/PreEQ ---
	MIDI_NOTEON_BOOST_TGL			= 27,
	MIDI_NOTEON_BOOST_ON			= 28,
	MIDI_NOTEON_BOOST_OFF			= 29,
	MIDI_NOTEON_OCTAVE_TGL			= 30,
	MIDI_NOTEON_OCTAVE_ON			= 31,
	MIDI_NOTEON_OCTAVE_OFF			= 32,
	// --- Delay buttons ---
	MIDI_NOTEON_DELAY_TGL			= 33,
	MIDI_NOTEON_DELAY_ON			= 34,
	MIDI_NOTEON_DELAY_OFF			= 35,
	MIDI_NOTEON_DELAY_TAP			= 36,
	MIDI_NOTEON_DELAY_FREEZE_TGL	= 37,
	MIDI_NOTEON_DELAY_FREEZE_ON		= 38,
	MIDI_NOTEON_DELAY_FREEZE_OFF	= 39,
	// --- Main Reverb buttons ---
	MIDI_NOTEON_REVERB_TGL			= 40,	// Main reverb bypass
	MIDI_NOTEON_REVERB_ON			= 41,
	MIDI_NOTEON_REVERB_OFF			= 42,
	MIDI_NOTEON_REVERB_FREEZE_TGL	= 43,	// Main reverb bypass
	MIDI_NOTEON_REVERB_FREEZE_ON	= 44,
	MIDI_NOTEON_REVERB_FREEZE_OFF	= 45,
	// --- Plate Reverb ----
	MIDI_NOTEON_REVERBPL_SET		= 46,	// Set Reverb: Plate
	// ReverbSC
	MIDI_NOTEON_REVERBSC_SET		= 47,	// Set Reverb: SC
	MIDI_NOTEON_REVERBSP_SET		= 48,	// Set Reverb: Spring
	// -- preset system ---
	MIDI_NOTEON_PRESET_1			= 50,
	MIDI_NOTEON_PRESET_2			= 51,
	MIDI_NOTEON_PRESET_3			= 52,
	MIDI_NOTEON_PRESET_4			= 53,
	MIDI_NOTEON_PRESET_5			= 54,
	MIDI_NOTEON_PRESET_6			= 55,
	MIDI_NOTEON_PRESET_7			= 56,
	MIDI_NOTEON_PRESET_8			= 57,
	MIDI_NOTEON_PRESET_SAVE			= 60,	

	MIDI_NOTEON_WAH_TGL				= 61,
	MIDI_NOTEON_WAH_ON				= 62,
	MIDI_NOTEON_WAH_OFF				= 63,
	MIDI_NOTEON_WAH_MODEL1			= 64,
	MIDI_NOTEON_WAH_MODEL2			= 65,
	MIDI_NOTEON_WAH_MODEL3			= 66,
	MIDI_NOTEON_WAH_MODEL4			= 67,
	MIDI_NOTEON_WAH_MODEL5			= 68,
	MIDI_NOTEON_WAH_MODEL6			= 69,
	MIDI_NOTEON_WAH_MODEL7			= 70,
	MIDI_NOTEON_WAH_MODEL8			= 71,


	// --- HW control buttons ---
	MIDI_NOTEON_CTRL_DRY			= 75,
	MIDI_NOTEON_CTRL_BYPASS			= 76,
	
	// --- diverse ---
	MIDI_NOTEON_TERMINAL_TGL		= 77,

	// --- Input selector ---
	MIDI_NOTEON_SELIN_LR			= 80,
	MIDI_NOTEON_SELIN_L				= 81,
	MIDI_NOTEON_SELIN_R				= 82,

	MIDI_NOTEON_MCU_RESET			= 127
};


#endif // _MIDI_H_
