#ifndef _PRESETDEFAULT_H_
#define _PRESETDEFAULT_H_

#include "presetSystem.h"

// using normalized parameters to store them as uint8_t instead of float

#define FLAG_DEFAULT_INPUT_SELECT			(AudioSwitchSelectorStereo::SIGNAL_SELECT_L)
#define FLAG_DEFAULT_FT1_ASSIGN				(PRESET_FTASSIGN_PRESET_UP)
#define FLAG_DEFAULT_FT2_ASSIGN				(PRESET_FTASSIGN_PRESET_DOWN)

#define PARAM_DEFAULT_COMP_PREGAIN 			(0.25f)		// rng= 0.0 to 4.0 0.25=>1.0
#define PARAM_DEFAULT_COMP_THRES 			(0.5f) 		// rng=0 to -40 0.5=>-20dB
#define PARAM_DEFAULT_COMP_RATIO 			(0.5f) 		// rng=0 to 10, 0.5 => 5.0
#define PARAM_DEFAULT_COMP_ATTACK 			(0.49f)		// rng=0.001 to 0.1 0.49=>0.005
#define PARAM_DEFAULT_COMP_RELEASE			(0.11f)		// rng=0.1 to 1.0. 0.11=>0.2
#define PARAM_DEFAULT_COMP_POSTGAIN			(0.25f)		// rng= 0.0 to 4.0 0.25=>1.0

#define PARAM_DEFAULT_WAH_FREQ				(0.5f)
#define PARAM_DEFAULT_WAH_MIX				(1.0f)
#define FLAG_DEFAULT_WAH_MODEL				(WAH_MODEL_G3)

#define PARAM_DEFAULT_BOOST_DRIVE			(1.0f)
#define PARAM_DEFAULT_BOOST_BOTTOM			(1.0f)
#define PARAM_DEFAULT_BOOST_PRESENCE		(1.0f)
#define PARAM_DEFAULT_BOOST_MIX				(1.0f)
#define PARAM_DEFAULT_BOOST_LEVEL			(1.0f)
#if defined(USE_SGTL5000) || defined(USE_ES8388)
#define PARAM_DEFAULT_GATE_THRES			(0.50f) // scaled to -40.0dB, range 0.0 to -100dB
#else
#define PARAM_DEFAULT_GATE_THRES			(0.73f)	// scaled to -73.0dB
#endif
#define PARAM_DEFAULT_AMP_GAIN				(1.0f)
#define PARAM_DEFAULT_AMP_BASS				(1.0f)
#define PARAM_DEFAULT_AMP_MID				(1.0f)
#define PARAM_DEFAULT_AMP_TREBLE			(1.0f)
#define PARAM_DEFAULT_AMP_FXMIX				(0.2f)

#define PARAM_DEFAULT_DELAY_TIME			(0.6f)
#define PARAM_DEFAULT_DELAY_INERTIA			(0.0f)
#define PARAM_DEFAULT_DELAY_REPEATS			(0.4f)
#define PARAM_DEFAULT_DELAY_MIX				(1.0f)
#define PARAM_DEFAULT_DELAY_HICUT			(0.0f)
#define PARAM_DEFAULT_DELAY_LOWCUT			(0.0f)
#define PARAM_DEFAULT_DELAY_TREBLE			(1.0f)
#define PARAM_DEFAULT_DELAY_BASS			(1.0f)
#define PARAM_DEFAULT_DELAY_MODRATE			(0.0f)
#define PARAM_DEFAULT_DELAY_MODDEPTH		(0.0f)

#define PARAM_DEFAULT_REVERBPL_SIZE			(0.8f)
#define PARAM_DEFAULT_REVERBPL_DIFF			(1.0f)
#define PARAM_DEFAULT_REVERBPL_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBPL_BASSCUT		(0.0f)
#define PARAM_DEFAULT_REVERBPL_TREBLECUT	(0.0f)		
#define PARAM_DEFAULT_REVERBPL_TREBLE		(1.0f)
#define PARAM_DEFAULT_REVERBPL_BASS			(1.0f)
#define PARAM_DEFAULT_REVERBPL_BLEEDIN		(0.0f)
#define PARAM_DEFAULT_REVERBPL_PITCH		(0.5f)
#define PARAM_DEFAULT_REVERBPL_PITCHMIX		(0.0f)
#define PARAM_DEFAULT_REVERBPL_SHIMMER		(0.0f)
#define PARAM_DEFAULT_REVERBPL_PITCHSHIMM	(0.5f)

#define PARAM_DEFAULT_REVERBSC_TIME			(0.7f)
#define PARAM_DEFAULT_REVERBSC_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBSC_LOWPASSF		(1.0f)

#define PARAM_DEFAULT_REVERBSP_TIME			(0.7f)
#define PARAM_DEFAULT_REVERBSP_MIX			(1.0f)
#define PARAM_DEFAULT_REVERBSP_BASSCUT		(0.4f)
#define PARAM_DEFAULT_REVERBSP_TREBLECUT	(0.3f)

#define PARAM_DEFAULT_MASTER_VOLUME			(1.0f)
#define PARAM_DEFAULT_MASTER_PAN			(0.5f)
#define PARAM_DEFAULT_DELAY_VOLUME			(0.2f)
#define PARAM_DEFAULT_REVERB_VOLUME			(0.2f)
#define PARAM_DEFAULT_MASTER_LOWCUT			(0.0f)

#define PARAM_DEFAULT_EXP_ASSIGN			(PRESET_PARAM_WAH_FREQ+1)

extern const preset_t presets_default[PRESET_MAX_NO_EEP];

#endif // _PRESETDEFAULT_H_
